project_name: woodwatch
builds:
  - main: ./cmd/woodwatch
    binary: woodwatch
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
archive:
  wrap_in_directory: true
  replacements:
    linux: Linux
    386: i386
    amd64: x86_64
  files:
    - LICENSE.txt
    - README.md
    - example.config.json
    - example.woodwatch.service
    - bless.sh
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
